[build-system]
requires = ["PyCyBase", "cython", "setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "PyDecisionGraph"
dynamic = ["version"]
description = "A rule-based decision tree implementation for Python"
readme = "README.md"
requires-python = ">=3.12"
license = "MPL-2.0"
license-files = ["LICENSE"]
authors = [{ name = "Han Bolun", email = "Bolun.Han@outlook.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
keywords = ["decision tree", "decision graph", "rules", "cython", "HFT"]
dependencies = []

[project.optional-dependencies]
visualization = [
    "flask",
    "jinja2"
]
session_time_support = [
    "PyAlgoEngine"
]

[project.urls]
Homepage = "https://github.com/BolunHan/PyDecisionGraph"
Repository = "https://github.com/BolunHan/PyDecisionGraph"
Issues = "https://github.com/BolunHan/PyDecisionGraph/issues"

[tool.setuptools.package-data]
"decision_graph.decision_tree.capi" = ["*.h", "*.pxd", "*.pyx", "*.pyi"]
"decision_graph.decision_tree.bake" = ["*.h", "*.pxd", "*.pyx", "*.pyi"]
"decision_graph.webui.capi" = ["templates/*.html", "static/*.css", "static/*.js"]
"decision_graph.webui.native" = ["templates/*.html", "static/*.css", "static/*.js"]
"decision_graph.webui.bake" = ["templates/*.html", "static/*.css", "static/*.js"]
"decision_graph" = [
    "includes/**/*.h",
    "includes/**/*.c",
    "includes/**/*.cpp",
]

[tool.setuptools.dynamic]
version = { attr = "decision_graph.__version__" }