"""Wrapper tests for ``decision_graph.decision_tree.bake.c_node``.

Scope is the Python surface only. The building rules themselves are settled by
``tests/bake/test_c_node_lifecycle.c`` and its siblings; what is checked here is
the wrapper's half of the bargain:

  - the base refuses to be built, because bake has no bare node type;
  - a concrete node adopts a block, and puts itself where a tree walk looks it
    up - the register design, which is what a parent syncs its children against;
  - a node's Python-side bookkeeping (``children``, ``parent``,
    ``condition_to_parent``) stays in step with the C tree across an append, a
    detach and a sync.

Only ``PlaceholderNode`` is built here, because it is the one concrete node the
node layer itself owns - the action family and the graph's own types are other
layers, and each family's own suite covers what it registers. That is enough to
exercise every path this module is responsible for.

Oracle: expected values come from the C node's own reported identity (its type
name, its uuid) and from the objects handed in, never from re-deriving the
wrapper's own arithmetic.
"""

import unittest
from uuid import UUID

from decision_graph.decision_tree.bake import c_node
from decision_graph.decision_tree.bake.c_edge import AUTO_CONDITION
from decision_graph.decision_tree.exc import NodeTypeError


class TestLogicNodeBase(unittest.TestCase):
    """Contract: the node base is not buildable on its own.

    Expected behavior:
        - instantiating ``LogicNode`` raises ``NodeTypeError``;
        - the message names the class, so a caller who reached for the base by
          mistake is told which one they got.

    Bake has no bare node type: every node belongs to a family, and a family is
    what gives it a type, an arity and a teardown.
    """

    def test_00_the_base_refuses_to_be_built(self) -> None:
        """Instantiating the base raises rather than making an untyped node."""
        with self.assertRaises(NodeTypeError):
            c_node.LogicNode()

    def test_01_the_refusal_names_the_class(self) -> None:
        """The error says which class was reached for."""
        with self.assertRaises(NodeTypeError) as ctx:
            c_node.LogicNode()
        self.assertIn('LogicNode', str(ctx.exception))


class TestPlaceholderNode(unittest.TestCase):
    """Contract: a placeholder is a plain, auto-generated, owned node.

    Expected behavior:
        - it adopts a block of its own, so it reports a live address and uuid;
        - it is ``autogen``, which is how consolidation tells it from a node a
          caller wrote;
        - it starts childless, so it reports as a leaf;
        - it has no children and no parent until something links it.

    The placeholder is the node layer's own concrete type - the action family
    does not own it - which is why the node layer can reserve its arms without
    naming a layer above it.
    """

    def test_00_a_fresh_placeholder_reports_its_type(self) -> None:
        """The type the C layer reports is the placeholder type."""
        node = c_node.PlaceholderNode()
        self.assertEqual(node.type, 'PLACEHOLDER')

    def test_01_a_fresh_placeholder_is_autogen(self) -> None:
        """A placeholder is auto-generated by definition."""
        node = c_node.PlaceholderNode()
        self.assertTrue(node.autogen)

    def test_02_a_fresh_placeholder_is_childless(self) -> None:
        """It reserves nothing of its own, so it is a leaf with no children."""
        node = c_node.PlaceholderNode()
        self.assertTrue(node.is_leaf)
        self.assertEqual(node.children, {})

    def test_03_a_fresh_placeholder_has_an_address_and_a_uuid(self) -> None:
        """It adopted a real block, and the block carries a minted identity."""
        node = c_node.PlaceholderNode()
        self.assertNotEqual(node.address, 0)
        self.assertIsInstance(node.uuid, UUID)

    def test_04_two_placeholders_are_distinct_nodes(self) -> None:
        """Each constructor call adopts its own block."""
        left = c_node.PlaceholderNode()
        right = c_node.PlaceholderNode()
        self.assertNotEqual(left.address, right.address)
        self.assertNotEqual(left.uuid, right.uuid)

    def test_05_a_placeholder_carries_the_default_display_text(self) -> None:
        """A placeholder has no repr to give: the C layer names it, and it keeps that.

        The constructor takes none, so the text is the one the node was minted
        with - a second name for a node the build is about to retire is not a
        thing a caller gets to set.
        """
        node = c_node.PlaceholderNode()
        self.assertEqual(node.repr, 'Placeholder')

    def test_06_repr_names_the_class_and_the_text(self) -> None:
        """``repr()`` shows what the node is and what it reads as."""
        node = c_node.PlaceholderNode()
        self.assertEqual(repr(node), "<PlaceholderNode('Placeholder')>")


class TestNodeRegistry(unittest.TestCase):
    """Contract: a node puts itself where a tree walk looks a header up.

    Expected behavior:
        - a freshly built node is in ``NODE_REGISTRY`` under its own address;
        - the entry is the very wrapper the caller holds, not a fresh view of
          the same C node.

    This is what lets the node layer find the wrapper of a child the C layer
    grew on its own without naming any family above it. A node that never
    registered raises KeyError the moment its parent syncs, which is the honest
    report of a wrapper that was never made.
    """

    def test_00_a_new_node_is_registered_under_its_address(self) -> None:
        """Building a node registers it by address."""
        node = c_node.PlaceholderNode()
        self.assertIn(node.address, c_node.NODE_REGISTRY)
        self.assertIs(c_node.NODE_REGISTRY[node.address], node)

    def test_01_the_registry_keeps_the_caller_s_instance(self) -> None:
        """The entry is the instance the caller holds, not a rebuilt equivalent."""
        node = c_node.PlaceholderNode()
        self.assertIs(c_node.NODE_REGISTRY[node.address], node)

    def test_02_two_nodes_register_under_two_keys(self) -> None:
        """Distinct nodes occupy distinct entries."""
        left = c_node.PlaceholderNode()
        right = c_node.PlaceholderNode()
        self.assertIs(c_node.NODE_REGISTRY[left.address], left)
        self.assertIs(c_node.NODE_REGISTRY[right.address], right)

    def test_03_a_rebuilt_wrapper_finds_its_parent(self) -> None:
        """A node rebuilt from C gets the wrapper of the parent it hangs from.

        The lookup is by the parent's header address, which is what the registry
        is keyed by - a wrapper is not an address, and a node that hangs from
        nothing has none to look up.
        """
        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()
        parent.append(child)
        address = child.address
        del c_node.NODE_REGISTRY[address]
        self.assertIs(c_node.NODE_REGISTRY[address].parent, parent)

    def test_04_a_rebuilt_wrapper_without_a_parent_has_none(self) -> None:
        """A node that hangs from nothing reports no parent, not an error."""
        node = c_node.PlaceholderNode()
        address = node.address
        del c_node.NODE_REGISTRY[address]
        self.assertIsNone(c_node.NODE_REGISTRY[address].parent)


class TestChildrenBookkeeping(unittest.TestCase):
    """Contract: ``children`` is a persistent map kept in step with the C tree.

    Expected behavior:
        - ``append`` links the child, records the edge it landed on, and
          updates both sides: the parent's map and the child's parent pointer;
        - the map is keyed by the condition object the edge carries;
        - ``detach`` unlinks the child and leaves the parent's map empty.

    The map holds the very wrapper instances the caller holds, which is what
    lets anything keyed on them stay meaningful; a map rebuilt on every read
    would not.
    """

    def test_00_append_records_the_child_on_its_edge(self) -> None:
        """An appended child appears in the parent's map under its linked edge.

        ``append`` hands the C layer an AUTO condition, which the C layer
        RESOLVES as it links - so the key is whatever the child reports, not the
        AUTO sentinel that was passed in.
        """
        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()
        parent.append(child)
        self.assertIs(parent.children[child.condition_to_parent], child)

    def test_01_append_sets_the_child_s_parent(self) -> None:
        """The child knows what it hangs off."""
        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()
        parent.append(child)
        self.assertIs(child.parent, parent)

    def test_02_append_resolves_the_auto_condition(self) -> None:
        """The edge a child reports is a resolved one, not the AUTO sentinel.

        AUTO means "infer it from the parent"; the C layer does that as it
        links, so what lands on the child is a concrete edge - and it is the
        same object the parent's map is keyed by.
        """
        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()
        parent.append(child)
        self.assertNotEqual(child.condition_to_parent, AUTO_CONDITION)
        self.assertIn(child.condition_to_parent, parent.children)

    def test_03_the_child_stops_being_a_leaf(self) -> None:
        """A parent with a child is not a leaf; the child still is."""
        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()
        parent.append(child)
        self.assertFalse(parent.is_leaf)
        self.assertTrue(child.is_leaf)

    def test_04_rshift_appends_the_same_way(self) -> None:
        """``>>`` is the same link, and hands the child back."""
        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()
        returned = parent >> child
        self.assertIs(returned, child)
        self.assertIs(parent.children[child.condition_to_parent], child)
        self.assertIs(child.parent, parent)

    def test_05_detach_unlinks_the_child(self) -> None:
        """A detached child has no parent and holds no edge."""
        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()
        parent.append(child)
        child.detach()
        self.assertIsNone(child.parent)
        self.assertEqual(parent.children, {})

    def test_06_detach_clears_the_edge_the_child_carried(self) -> None:
        """The detached child no longer claims an edge to its former parent."""
        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()
        parent.append(child)
        child.detach()
        self.assertNotEqual(child.condition_to_parent, AUTO_CONDITION)


class TestEnteringANode(unittest.TestCase):
    """Contract: only a node that can hold a branch may be entered.

    Expected behavior:
        - entering a placeholder raises ``NodeTypeError``, because a stand-in
          is not a place a build continues from.

    A placeholder is what an unfinished branch left behind; descending into it
    would build under a node that consolidation is about to retire.
    """

    def test_00_a_placeholder_refuses_to_be_entered(self) -> None:
        """A ``with`` block inside a placeholder is refused.

        The refusal is the C layer's now: a placeholder's context enter returns
        DCG_ERR_TYPE, so it arrives as the manager's RuntimeError rather than a
        check the wrapper makes before calling in.
        """
        node = c_node.PlaceholderNode()
        with self.assertRaises(RuntimeError):
            with node:
                pass


class TestLabels(unittest.TestCase):
    """Contract: labels are a name set the caller can add to and read back.

    Expected behavior:
        - a fresh node has no labels;
        - ``label`` adds one, ``has_label`` reports it, ``labels`` lists it;
        - ``unlabel`` removes it again;
        - adding the same label twice does not report it twice.

    Labels are free-form names a caller hangs on a node; they are not the
    node's identity, which is its uuid.
    """

    def test_00_a_fresh_node_has_no_labels(self) -> None:
        """Nothing is labelled until the caller says so."""
        node = c_node.PlaceholderNode()
        self.assertEqual(node.labels, [])

    def test_01_a_label_round_trips(self) -> None:
        """An added label is reported by both accessors."""
        node = c_node.PlaceholderNode()
        node.label('entry')
        self.assertTrue(node.has_label('entry'))
        self.assertEqual(node.labels, ['entry'])

    def test_02_an_absent_label_is_reported_absent(self) -> None:
        """A name that was never added is not claimed."""
        node = c_node.PlaceholderNode()
        node.label('entry')
        self.assertFalse(node.has_label('exit'))

    def test_03_unlabel_removes_the_name(self) -> None:
        """Removing a label takes it out of the set it was in."""
        node = c_node.PlaceholderNode()
        node.label('entry')
        node.unlabel('entry')
        self.assertFalse(node.has_label('entry'))
        self.assertEqual(node.labels, [])

    def test_04_a_repeated_label_is_refused(self) -> None:
        """The same name cannot be added twice - the second add is an error.

        A label is a set entry, so re-adding one is a contract violation the C
        layer reports rather than a no-op it silently absorbs.
        """
        node = c_node.PlaceholderNode()
        node.label('entry')
        with self.assertRaises(RuntimeError):
            node.label('entry')
        self.assertEqual(node.labels, ['entry'])

    def test_05_two_labels_are_both_kept(self) -> None:
        """The set holds every name added, not just the newest."""
        node = c_node.PlaceholderNode()
        node.label('entry')
        node.label('long')
        self.assertEqual(sorted(node.labels), ['entry', 'long'])


class TestQueries(unittest.TestCase):
    """Contract: a node can report its own shape and whether it is well-formed.

    Expected behavior:
        - ``size`` counts the subtree the node roots, itself included;
        - ``render`` returns console text without writing anything itself;
        - ``validate`` returns ``None`` for a well-formed graph and a report
          otherwise - a parentless non-root node is a detached fragment, and
          that is a report.
    """

    def test_00_a_lone_node_has_size_one(self) -> None:
        """A node with no children is a subtree of one."""
        node = c_node.PlaceholderNode()
        self.assertEqual(node.size, 1)

    def test_01_size_grows_with_the_subtree(self) -> None:
        """An appended child is part of the subtree its parent roots."""
        parent = c_node.PlaceholderNode()
        parent.append(c_node.PlaceholderNode())
        self.assertEqual(parent.size, 2)

    def test_02_render_returns_text_naming_the_node(self) -> None:
        """The render is text, and it shows the node's display text."""
        node = c_node.PlaceholderNode()
        rendered = node.render()
        self.assertIsInstance(rendered, str)
        self.assertIn('Placeholder', rendered)

    def test_03_a_detached_node_is_reported_as_unwell_formed(self) -> None:
        """A parentless node that is not a root validates with a report.

        ``validate`` returns None when the graph is sound; anything else means
        a rule broke, which is the honest answer for a fragment nothing is
        holding.
        """
        node = c_node.PlaceholderNode()
        self.assertIsNotNone(node.validate())


class TestTheEdgeAnAppendTakes(unittest.TestCase):
    """Contract: ``append``'s default edge is the auto edge, and it is a real one.

    Expected behavior:
        - the parameter's default IS ``AUTO_CONDITION``, not a sentinel that is
          quietly replaced - which is what the signature now says and what a
          caller reading it is owed;
        - ``node.append(child)`` and ``node >> child`` therefore link a child the
          same way, since both hand the arm to the parent to work out;
        - an append that names an arm takes that arm, with nothing inferred.

    The capi is the oracle for the signature: its ``LogicNode.append`` has taken
    ``AUTO_CONDITION`` as its default since before this layer existed, so a build
    ported between the two layers appends the same way in both. Before this, the
    two agreed on what they DID - the body already used the auto edge - and
    disagreed on what they SAID, which is the half a caller reads.
    """

    def test_00_the_default_is_the_auto_edge(self) -> None:
        """The signature says what the body does."""
        import inspect

        default = inspect.signature(c_node.LogicNode.append).parameters['condition'].default
        self.assertIs(default, AUTO_CONDITION)

    def test_01_an_unconditioned_append_lets_the_parent_infer_the_arm(self) -> None:
        """The first child of a fresh parent takes the TRUE arm of a pair.

        The auto edge is resolved WHERE the child joins: the parent works the arm
        out from what it already holds, so what ``children`` ends up keyed by is
        the arm itself and never the auto edge.
        """
        from decision_graph.decision_tree.bake.c_edge import TRUE_CONDITION

        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()

        parent.append(child)
        self.assertIs(parent.children[TRUE_CONDITION], child)
        self.assertIs(child.parent, parent)

    def test_02_the_shift_operator_links_by_the_same_edge(self) -> None:
        """``>>`` is the auto edge written as an operator, and it says so."""
        by_append = c_node.PlaceholderNode()
        by_shift = c_node.PlaceholderNode()
        left, right = c_node.PlaceholderNode(), c_node.PlaceholderNode()

        by_append.append(left)
        self.assertIs(by_shift.__rshift__(right), right)
        self.assertEqual(
            [str(edge) for edge in by_append.children],
            [str(edge) for edge in by_shift.children],
        )

    def test_03_an_append_that_names_an_arm_takes_that_arm(self) -> None:
        """An explicit edge is not inferred over."""
        from decision_graph.decision_tree.bake.c_edge import ELSE_CONDITION

        parent = c_node.PlaceholderNode()
        child = c_node.PlaceholderNode()

        parent.append(child, ELSE_CONDITION)
        self.assertIs(parent.children[ELSE_CONDITION], child)
